[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" # prevents Netlify from running npm install
  PNPM_FLAGS = "--version" # prevents Netlify from running pnpm install incorrectly

[[plugins]]
  package = "@netlify/plugin-nextjs"
